# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py39

# Defaults should be serial, but weird failures motivate forcing this?
[testenv]
basepython = python3.9
commands = 
    nosetests -vv --collect-only {toxinidir}/tests/baud_tests.py {toxinidir}/tests/chip_id_tests.py {toxinidir}/tests/gdb_session_test.py {toxinidir}/tests/gdb_simple_test.py {toxinidir}/tests/ice_tests.py {toxinidir}/tests/mbus_write_test.py {toxinidir}/tests/timeout_test.py
    nosetests --processes=0 {toxinidir}/tests/baud_tests.py {toxinidir}/tests/chip_id_tests.py {toxinidir}/tests/gdb_session_test.py {toxinidir}/tests/gdb_simple_test.py {toxinidir}/tests/ice_tests.py {toxinidir}/tests/mbus_write_test.py {toxinidir}/tests/timeout_test.py
deps =
    nose
    pyserial
